modelname: 'GATHAR_with_e_15_l_5154test'
num_epochs: 100
seed: 5154
train_proportion: 0.7
validation_proportion: 0.1
use_har_features: false
include_energy: false
loss_function: 'mse'  
seq_length: 15
grid:
  - hidden_layout
  - num_heads
  - learning_rate
  - dropout
  - batch_size
  - optimizer
  - activation
  - lambda_weight
  - loss_function
  - seq_length
  
hyperparameters:

  hidden_layout:
    - [ [256, 128, 64], 
        [192, 96, 48], 
        [128, 64, 32], 
        [256, 128], 
        [192, 96], 
        [128, 64],
        [256, 256, 256], 
        [128, 128, 128], 
        [64, 64, 64] 
      ]
    - cat
 
  num_heads:
    - [2, 8]
    - int

  learning_rate:
    - [0.0001, 0.01]
    - float
 
  dropout:
    - [0.05, 0.5]
    - float
 
  batch_size:
    - [16, 32, 64, 128, 256]
    - cat

  lambda_weight:
    - [0.1, 0.9]
    - float
   
  optimizer:
    - ['adam', 'adamw', 'rmsprop']
    - cat
 
  activation:
    - ['relu', 'leaky_relu', 'tanh']
    - cat

  loss_function:
    - ['mse', 'qlike']
    - cat

node_info_file: './node_info.json'
hdf5_file_vol_std: './processed_data1001/vol_covol_standardized.h5'
hdf5_file_volvol_std: './processed_data1001/volvol_covolvol_standardized.h5'
stock_har_rv_folder: './day/standardized_stock_har'
energy_har_rv_folder: './day/standardized_energy_har'
stock_energy_corr_folder: './day/daycorr_stock_energy'
energy_energy_corr_folder: './day/daycorr_energy_energy'
intraday_points: 3
n_trials: 100